# Generated by Django 5.0.7 on 2024-07-17 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileapp', '0002_alter_file_file_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_content',
            field=models.FileField(upload_to='uploaded_files/'),
        ),
    ]
